build: bump version to 0.7.2
fixup publish problem:

```shell
❯ cargo publish --dry-run
    Updating crates.io index
   Packaging git-cz v0.7.1 (/home/ttys3/repo/rust/git-cz)
error: failed to prepare local package for uploading

Caused by:
  failed to select a version for `dialoguer`.
      ... required by package `git-cz v0.7.1 (/home/ttys3/repo/rust/git-cz)`
  versions that meet the requirements `^0.8.0` are: 0.8.0

  the package `git-cz` depends on `dialoguer`, with features: `fuzzy-select` but `dialoguer` does not have these features.

  failed to select a version for `dialoguer` which could resolve this conflict
```